name: checkbox_grouped
on: [ push, pull_request ]

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: export tag
        run: echo "RELEASE_VERSION=v${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: preparation
        uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration": 1583530852703
          }
          EOF
      - name: Publish package
        run: pub publish -f
      - name: release version
        uses: ncipollo/release-action@v1
        with:
            tag: {{ env.RELEASE_VERSION }}
            name: {{ env.RELEASE_VERSION }}
            token: {{ secrets.GITHUB_TOKEN }}